version: '3.8'

services:
  mongodb-data:
    container_name: mongodb-data
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/DATA:/data
    networks:
      backend:
        aliases:
          - "mongodb-data"

  redis-session:
    container_name: redis-session
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ~/SESSION:/session
    networks:
      backend:
        aliases:
          - "redis-session"

  service-reading-is-good:
    depends_on:
      - mongodb-data
      - redis-session
    container_name: service-reading-is-good
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "service-reading-is-good"
networks:
  backend:
    driver: bridge