version: '3.8'

services:
  mongodb-data:
    container_name: mongodb-data
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/DATA/mongo:/data/db
    networks:
      backend:
        aliases:
          - "mongodb-data"

  service-backend:
    depends_on:
      - mongodb-data
    container_name: service-backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "service-backend"
networks:
  backend:
    driver: bridge