version: '3.8'

services:

  service-backend:
    container_name: service-backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: reading-is-good-network