spring:
  data:
    mongodb:
      uri: mongodb://mongodb-data-1:27017/reading-is-good
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: error

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  show-login-endpoint: false

session:
  excluded-paths:
    - /swagger-ui*/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /webjars/**