spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reading-is-good
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG